HOME=/home/mersault

include $(GOROOT)/src/Make.inc
TARG=v8
include $(GOROOT)/src/Make.pkg

swig:
	swig -c++ -go v8.i

build: swig
	g++ -c -I$(HOME)/svn/v8/src -fpic v8_wrap.cxx
	g++ -shared v8_wrap.o -o v8.so
	8g v8.go
	8c -I$(HOME)/hg/go/src/pkg/runtime v8_gc.c
	gopack grc v8.a v8.8 v8_gc.8
	8g -I. v8main.go
	8l -L. v8main.8

# Override default definition of clean from Go build scripts in order to make sure
# we clean up C++ code generated by SWIG as well
clean:
	rm -f v8_wrap.cxx v8_gc.c v8.go
	rm -f v8_wrap.o v8_gc.8 v8.8
	rm -f v8.so v8.a
	rm -f v8main.8 8.out

